
# Stage 1: Build the application
FROM amazoncorretto:17 AS build
WORKDIR /app
COPY . .
RUN ./mvnw package

# Stage 2: Create the final runtime image
FROM amazoncorretto:17 AS runtime
WORKDIR /app
COPY --from=build /app/target/*.jar app.jar
ENTRYPOINT ["java","-jar","/app.jar"]